### ISSUE TITLE
Aanpassing IPTV-route

### ISSUE THREAD

**Issue by friek** [machuidel/openwrt-sparql#1]
De route voor 185.6.48.0/26 klopt heel binnenkort niet meer. Het beste is om helemaal geen static routes meer toe te voegen, maar DHCP optie 121 (classless static routes) te accepteren en zo automatisch routes te laten installeren die door de Tweak DHCP-server worden verstrekt.
Ik weet niet of de OpenWRT DHCP-client dit ondersteunt, dus dat moet je nog ff uitzoeken.

**Comment by machuidel** [comment]
Ik heb al een tijdje geen IPTV meer bij Tweak, maar alleen nog Internet en VOIP (siproxy op router en eigen Asterisk)

OpenWRT ondersteund de 121 optie:
https://openwrt.org/docs/guide-user/network/ipv4/start

**Comment by friek** [comment]
Ok. Helaas moet dat wel handmatig worden aangezet.

**Comment by machuidel** [comment]
Met een paar kleine aanpassingen wel. Bedankt voor de input.
